// <auto-generated />
using System;
using MMSystem.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace External_Party.Migrations
{
    [DbContext(typeof(AppDbCon))]
    partial class AppDbConModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MMSystem.Model.External_Party", b =>
                {
                    b.Property<int>("External_Party_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("External_Party_ID"));

                    b.Property<string>("External_Party_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("state")
                        .HasColumnType("bit");

                    b.HasKey("External_Party_ID");

                    b.ToTable("External_Parties");
                });

            modelBuilder.Entity("MMSystem.Model.External_Party_Users", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<int>("External_Party_ID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("state")
                        .HasColumnType("bit");

                    b.HasKey("User_ID");

                    b.HasIndex("External_Party_ID");

                    b.ToTable("External_Party_Users");
                });

            modelBuilder.Entity("MMSystem.Model.Mail_Of_External", b =>
                {
                    b.Property<int>("ExMailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExMailID"));

                    b.Property<DateTime>("Date_Of_Mail")
                        .HasColumnType("datetime2");

                    b.Property<int>("External_Party_ID")
                        .HasColumnType("int");

                    b.Property<string>("Mail_Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clasification")
                        .HasColumnType("int");

                    b.Property<bool>("state")
                        .HasColumnType("bit");

                    b.HasKey("ExMailID");

                    b.HasIndex("External_Party_ID");

                    b.ToTable("Mail_Of_Externals");
                });

            modelBuilder.Entity("MMSystem.Model.External_Party_Users", b =>
                {
                    b.HasOne("MMSystem.Model.External_Party", "ExternalParty")
                        .WithMany("Users")
                        .HasForeignKey("External_Party_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalParty");
                });

            modelBuilder.Entity("MMSystem.Model.Mail_Of_External", b =>
                {
                    b.HasOne("MMSystem.Model.External_Party", "ExternalParty")
                        .WithMany("Mails")
                        .HasForeignKey("External_Party_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalParty");
                });

            modelBuilder.Entity("MMSystem.Model.External_Party", b =>
                {
                    b.Navigation("Mails");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
